{{-- Plain-text body for an automated report (App\Mail\ScheduledReportMail).

     Every line below describes the SCOPE of the attached file. None of them
     contains a record from it — see the note on the Mailable for why that
     boundary is the point of this template rather than an accident of it. --}}
Barangay 178, North Caloocan
Crime Data Analytics & Reporting System

This is an automated report generated by the CDARS reporting schedule
"{{ $scheduleName }}".

Report:     {{ $reportLabel }}
Scope:      {{ $scopeSummary }}
Records:    {{ $rowCount }}
Generated:  {{ $generatedAt }}

The report is attached as a CSV file.

This message was generated automatically. Please do not reply to it.
To change or stop this schedule, sign in to CDARS and open
Settings > Scheduled Reports.
